[URL]
; DefaultEngine settings for LookSpace prototype

[/Script/Engine.RendererSettings]
r.DefaultFeature.Lumen=True
r.Nanite=True
r.VolumetricFog=True

[SystemSettings]
foliage.MinTimeBetweenHashedFrames=5
